#!/bin/bash
echo Starting Execution!

if [ "$1" == "install" ];
then
	echo Beginning install process
	pip install GitPython
	python3 setup.py
	npm install typescript
	npm install fs
	npm install readline
	npm install python-shell
	npm install dotenv
	npm install @octokit/rest
	npm install @octokit/core
	npm install @octokit/request
	npm install types
	npm i --save-dev @types/node

elif [ "$1" == "build" ];
then
	echo Beginning build process
	tsc src/npmToGithub.ts
	tsc src/licRespFetch.ts
	tsc src/busfactor.ts
elif [ "$1" == "test" ];
then
	echo Beginning test process
else
	echo Running main program
	echo File location: $1
	node src/npmToGithub.js $1
	python3 fileCounter.py
	echo Finished Running
	 
fi

